version: v0.8.0-alpha.2

log:
  level: debug

namespaces:
  - id: 0
    name: permission
  - id : 1
    name : role

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: memory
